# Generated by Django 5.2 on 2025-04-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_usersessionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersessionlog',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
