# Generated by Django 5.2 on 2025-04-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_usersessionlog_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersessionlog',
            name='login_time',
            field=models.DateTimeField(),
        ),
    ]
