# Generated by Django 5.2 on 2025-04-18 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_alter_usersessionlog_login_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='image',
        ),
    ]
